### ISSUE TITLE
Stacktrace on first `import-data` command

### ISSUE THREAD

**Issue by distortedsignal** [opencve/opencve#130]
## Expected Behavior
When I run the command `opencve import-data --confirm`, I expect the command to complete without throwing a stacktrace.

## Actual Behavior
When I run the command `opencve import-data --confirm`, I see the following stacktrace:

```
...
[2021-08-11 21:39:29,404: INFO/ForkPoolWorker-1] HANDLE_EVENTS[db1b71ca-13af-460f-9bc3-3c1674c361c5]: Downloading https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta...
[2021-08-11 21:39:29,910: ERROR/ForkPoolWorker-1] Task HANDLE_EVENTS[db1b71ca-13af-460f-9bc3-3c1674c361c5] raised unexpected: AttributeError("'NoneType' object has no attribute 'value'")
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/opencve/tasks/events.py", line 94, in handle_events
    current_sum, new_sum = has_changed()
  File "/usr/lib/python3.9/site-packages/opencve/tasks/events.py", line 33, in has_changed
    if nvd_sha256 != last_nvd256.value:
AttributeError: 'NoneType' object has no attribute 'value'
 (done in 694.196s).
...
```

## Steps to Reproduce the Problem
I was using a dockerfile/container image to repro the issue. The dockerfile is here:

```
# Latest alpine at time of development
FROM alpine:latest

RUN apk add postgresql postgresql-contrib redis python3 py3-pip postgresql-libs postgresql-dev && \
        apk add --virtual .build-deps --no-cache gcc musl-dev libffi-dev openssl-dev python3-dev rust cargo && \
        pip3 install wheel six && \
        pip3 install opencve && \
        apk del .build-deps && \
        ln -sf python3 /usr/bin/python

ADD entrypoint.sh /run/entrypoint/entrypoint.sh
RUN mkdir -p /run/postgresql /home/postgres && \
        chown -R postgres:postgres /home/postgres && \
        chown -R postgres:postgres /run/postgresql && \
        chmod a+x /run/entrypoint/entrypoint.sh

EXPOSE 9000/tcp
EXPOSE 9000/udp

ENTRYPOINT [ "/run/entrypoint/entrypoint.sh" ]

```

And the entrypoint script is here:

```sh
#! /bin/sh

function make_run_as_cmd() {
    echo "su -l -" $1 "-c "
}

RUN_AS_PG=$(make_run_as_cmd "postgres")

OPENCVE_CFG_LOCATION="/var/lib/postgresql/opencve/opencve.cfg"

$RUN_AS_PG "pg_ctl init -D /home/postgres"
$RUN_AS_PG "pg_ctl start -D /home/postgres"
$RUN_AS_PG "psql -c \"CREATE DATABASE opencve\" template1"

$RUN_AS_PG "opencve init"
$RUN_AS_PG "sed -e 's/^database_uri.*$/database_uri = postgresql:\/\/localhost:5432\/opencve/g' $OPENCVE_CFG_LOCATION | sed -e 's/^server_name.*$/server_name = localhost:9000/g' >> $OPENCVE_CFG_LOCATION.final"
$RUN_AS_PG "mv $OPENCVE_CFG_LOCATION.final $OPENCVE_CFG_LOCATION"
$RUN_AS_PG "opencve upgrade-db"
$RUN_AS_PG "redis-server &"
sleep 5
$RUN_AS_PG "opencve celery worker -l INFO &"
$RUN_AS_PG "opencve celery beat -l INFO &"

$RUN_AS_PG "opencve create-user --admin --password admin admin admin@example.com"

$RUN_AS_PG "opencve import-data --confirm"

$RUN_AS_PG "opencve webserver -b 0.0.0.0:9000"

```

I believe that the steps to repro are as follows:

  - mkdir $my_dockerfiles/opencve
  - touch $my_dockerfiles/opencve/Dockerfile $my_dockerfiles/opencve/entrypoint.sh
  - Copy dockerfile and entrypoint script from above into appropriate files
  - docker build -t $my_docker_user/opencve $my_dockerfiles/opencve
  - docker run -it --rm -p 9000:9000 $my_docker_user/opencve

## Specifications

  - OpenCVE version: 1.2.0
  - Python version: 3.9
  - Platform: Alpine linux?

## Other

I've got this as a diff, but I can't seem to get it to stick:

```py
diff --git a/opencve/tasks/events.py b/opencve/tasks/events.py
index c3e592d..7bad816 100644
--- a/opencve/tasks/events.py
+++ b/opencve/tasks/events.py
@@ -18,6 +18,7 @@ NVD_MODIFIED_URL = "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.
 NVD_MODIFIED_META_URL = (
     "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta"
 )
+NDV_MODIFIED_META_RECORD_NAME="nvd_last_sha256"
 logger = get_task_logger(__name__)


@@ -28,7 +29,14 @@ def has_changed():

     matches = re.match(r".*sha256:(\w{64}).*", buf, re.DOTALL)
     nvd_sha256 = matches.group(1)
-    last_nvd256 = Meta.query.filter_by(name="nvd_last_sha256").first()
+    last_nvd256 = Meta.query.filter_by(name=NDV_MODIFIED_META_RECORD_NAME).first()
+
+    if last_nvd256 is None:
+        logger.info(
+            "Failed to find old nvd hash - " +
+            "assuming this is a fresh database import."
+        )
+        return None, nvd_sha256

     if nvd_sha256 != last_nvd256.value:
         logger.info(
@@ -94,6 +102,10 @@ def handle_events():
     current_sum, new_sum = has_changed()
     if not new_sum:
         return
+
+    if current_sum is None:
+        current_sum = Meta()
+        current_sum.name = NDV_MODIFIED_META_RECORD_NAME

     # Retrieve the list of modified CVEs
     logger.info("Download modified CVEs...")
```

I noticed that there is no row in the metas table with that name on first load, so there's potentially a way to fix this by inserting a row into the metas table. But this way might also work.

**Comment by ncrocfer** [comment]
Hello,

Your entrypoint contains the following lines:

```
$RUN_AS_PG "opencve celery worker -l INFO &"
$RUN_AS_PG "opencve celery beat -l INFO &"
$RUN_AS_PG "opencve create-user --admin --password admin admin admin@example.com"
$RUN_AS_PG "opencve import-data --confirm"
$RUN_AS_PG "opencve webserver -b 0.0.0.0:9000"
```

It's not valid, you have to first run the `import-data` command to populate the database (and so the `metas` table and `nvd_last_sha256` item), then you can run the worker and the beat. It's written in the [install documentation](https://docs.opencve.io/installation/manual/).

Here, because the worker and the beat are started first, the Celery tasks are launched but the database is still empty so your bug is normal.

For information we also provide a [docker repository](https://github.com/opencve/opencve-docker).
