### ISSUE TITLE
Celery_worker error

### ISSUE THREAD

**Issue by whh6tl** [opencve/opencve#161]
Celery_worker has the following error when I use docker deployment
`[2021-12-22 08:24:47,163: INFO/MainProcess] Received task: CVE_UPDATES[77903b95-7957-437d-985d-2dd175212d28]  
[2021-12-22 08:24:47,171: INFO/MainProcess] Received task: HANDLE_EVENTS[06bd7f2b-f8a8-4562-8106-e8fe73dfe093]  
[2021-12-22 08:24:47,172: INFO/ForkPoolWorker-1] Task CVE_UPDATES[77903b95-7957-437d-985d-2dd175212d28] succeeded in 0.006914749988936819s: <AsyncResult: 498609b7-1dba-4c96-936b-0343d443b093>
[2021-12-22 08:24:47,173: INFO/ForkPoolWorker-1] HANDLE_EVENTS[06bd7f2b-f8a8-4562-8106-e8fe73dfe093]: Checking for new events...
[2021-12-22 08:24:47,174: INFO/ForkPoolWorker-1] HANDLE_EVENTS[06bd7f2b-f8a8-4562-8106-e8fe73dfe093]: Downloading https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta...
[2021-12-22 08:24:48,261: ERROR/ForkPoolWorker-1] Task HANDLE_EVENTS[06bd7f2b-f8a8-4562-8106-e8fe73dfe093] raised unexpected: AttributeError("'NoneType' object has no attribute 'value'")
Traceback (most recent call last):
  File "/app/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/venv/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/venv/lib/python3.7/site-packages/opencve/tasks/events.py", line 94, in handle_events
    current_sum, new_sum = has_changed()
  File "/app/venv/lib/python3.7/site-packages/opencve/tasks/events.py", line 33, in has_changed
    if nvd_sha256 != last_nvd256.value:
AttributeError: 'NoneType' object has no attribute 'value'
`

**Comment by whh6tl** [comment]
![image](https://user-images.githubusercontent.com/54968227/147061492-5b473948-a106-4185-a147-18f769e3bd44.png)

**Comment by ncrocfer** [comment]
Check this: https://github.com/opencve/opencve/issues/67

**Comment by whh6tl** [comment]
The problem was solved by adding memory, thank you
