### ISSUE TITLE
Sign in to your account : Internal Server Error

### ISSUE THREAD

**Issue by focheur91300** [opencve/opencve#196]
Hello,

I am experiencing an authentication problem on the docker version of the product.

Here is the information below.

## Expected Behavior

Successful connection.

## Actual Behavior

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

## Steps to Reproduce the Problem

  - Login to : https://opencve.domain.priv/login

## Specifications

  - OpenCVE version: 1.3.0
  - Platform: Docker docker-compose build

## Log docker web

```
[2022-05-12 11:59:36,075] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column users.settings does not exist
LINE 1: ...ers_notifications AS users_filters_notifications, users.sett...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/venv/lib/python3.7/site-packages/flask_user/user_manager.py", line 416, in login_stub
    return self.login_view()
  File "/app/venv/lib/python3.7/site-packages/flask_user/user_manager__views.py", line 379, in login_view
    if request.method == 'POST' and login_form.validate():
  File "/app/venv/lib/python3.7/site-packages/flask_user/forms.py", line 190, in validate
    user = user_manager.db_manager.find_user_by_username(self.username.data)
  File "/app/venv/lib/python3.7/site-packages/flask_user/db_manager.py", line 138, in find_user_by_username
    return self.db_adapter.ifind_first_object(self.UserClass, username=username)
  File "/app/venv/lib/python3.7/site-packages/flask_user/db_adapters/sql_db_adapter.py", line 139, in ifind_first_object
    return query.first()
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3215, in first
    ret = list(self[0:1])
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3007, in __getitem__
    return list(res)
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/app/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column users.settings does not exist
LINE 1: ...ers_notifications AS users_filters_notifications, users.sett...
                                                             ^

[SQL: SELECT users.is_active AS users_is_active, users.id AS users_id, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.username AS users_username, users.password AS users_password, users.reset_password_token AS users_reset_password_token, users.email AS users_email, users.email_confirmed_at AS users_email_confirmed_at, users.enable_notifications AS users_enable_notifications, users.filters_notifications AS users_filters_notifications, users.settings AS users_settings, users.frequency_notifications AS users_frequency_notifications, users.first_name AS users_first_name, users.last_name AS users_last_name, users.admin AS users_admin
FROM users
WHERE users.username ILIKE %(username_1)s
 LIMIT %(param_1)s]
[parameters: {'username_1': 'admin', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by ncrocfer** [comment]
Apparently the database has not been initialized. Did you follow the documentation? https://docs.opencve.io/installation/docker/#initialize-the-database

**Comment by focheur91300** [comment]
Hello,

Thanks for the feedback.

It works.
