### ISSUE TITLE
Unable to complete data import at install stage

### ISSUE THREAD

**Issue by theslothuk** [opencve/opencve#208]
## Expected Behavior
Successful completion of command:
opencve import-data

## Actual Behavior
opencve import-data fails with below errors:

#####################
Importing CPE list...
#####################
[*] Downloading https://nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml.gz... (done in 1.415s).
[*] Parsing XML elements... (done in 264.238s).
[*] Creating list of mappings...[SQL: INSERT INTO vendors (id, created_at, updated_at, name) VALUES (%(id)s, now(), now(), %(name)s)] (done in 317.134Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1224, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 725, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.DatabaseError: could not receive data from server: Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/opencve", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/opencve/commands/__init__.py", line 39, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/opencve/commands/imports/__init__.py", line 42, in import_data
    cpe.run(vendors)
  File "/usr/local/lib/python3.6/site-packages/opencve/commands/imports/cpe.py", line 63, in run
    db.session.bulk_insert_mappings(Vendor, mappings["vendors"].values())
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2790, in bulk_insert_mappings
    render_nulls,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2880, in _bulk_save_mappings
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2874, in _bulk_save_mappings
    render_nulls,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 102, in _bulk_insert
    bookkeeping=return_defaults,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1066, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1224, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 725, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.DatabaseError: (psycopg2.DatabaseError) could not receive data from server: Connection timed out

[SQL: INSERT INTO vendors (id, created_at, updated_at, name) VALUES (%(id)s, now(), now(), %(name)s)]
[parameters: ({'id': UUID('b3137f1c-057c-4ec1-8b9c-6bffc84733ff'), 'name': 'openbsd'}, {'id': UUID('505627ca-56da-41fd-a6ec-f947e7ab8266'), 'name': 'bsdi'}, {'id': UUID('e051da69-0e24-4493-8056-a29363973bdd'), 'name': 'freebsd'}, {'id': UUID('0cfb3075-1b74-4dd0-9f42-0c06fcbefcda'), 'name': 'redhat'}, {'id': UUID('24c4a745-a31f-4f41-8117-6493d381b482'), 'name': 'caldera'}, {'id': UUID('74cb80a8-7980-49c0-9d69-3be85b50a418'), 'name': 'ibm'}, {'id': UUID('b7ae2b87-c389-47ee-97bd-e5711823350b'), 'name': 'sun'}, {'id': UUID('d77ea38a-acbf-4309-956c-d5b1d569e45c'), 'name': 'sgi'}  ... displaying 10 of 28066 total bound parameter sets ...  {'id': UUID('b6e11322-2b7b-4174-a730-d99d2cb52ccb'), 'name': 'zendesk_feedback_tab_project'}, {'id': UUID('d824a022-dca1-4fea-9b0c-688ab82f1778'), 'name': 'zyzel'})]
(Background on this error at: http://sqlalche.me/e/4xp6)

## Steps to Reproduce the Problem
Run:

opencve import-data
  - 
  - 
  - 

## Specifications

  - OpenCVE version: latest
  - Python version: 3.6
  - Platform: Linux Centos 8

**Comment by ncrocfer** [comment]
Closing this issue as it has been inactive for a long time and it's linked to OpenCVE v1 which is no more supported.
