### ISSUE TITLE
Docker Installation failed

### ISSUE THREAD

**Issue by hugohlr** [opencve/opencve#231]
![image](https://user-images.githubusercontent.com/56320554/193841498-cbb3a7f9-bdba-4897-82c0-099bca6e3611.png)

Hello, when I want to install OpenCVE via Docker, when I start the containers, webserver and celery-worker they do not want to start and print this error message:
Traceback (most recent call last):
  File "/app/venv/bin/opencve", line 11, in <module>
    load_entry_point('opencve==1.3.0', 'console_scripts', 'opencve')()
  File "/app/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/app/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/app/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/app/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/app/venv/lib/python3.7/site-packages/opencve/__init__.py", line 7, in <module>
    from opencve.api import api_bp
  File "/app/venv/lib/python3.7/site-packages/opencve/api/__init__.py", line 4, in <module>
    from opencve.api.alerts import AlertListResource, AlertResource
  File "/app/venv/lib/python3.7/site-packages/opencve/api/alerts.py", line 4, in <module>
    from opencve.api.base import BaseResource
  File "/app/venv/lib/python3.7/site-packages/opencve/api/base.py", line 7, in <module>
    from opencve.extensions import limiter
  File "/app/venv/lib/python3.7/site-packages/opencve/extensions.py", line 1, in <module>
    from celery import Celery
ImportError: cannot import name 'Celery' from 'celery' (/app/venv/lib/python3.7/site-packages/celery/__init__.py)

**Comment by therob89** [comment]
Modify the first line of Dockerfile as follow:

`FROM python:3.8.14-slim-buster as base`

and the containers will start correctly.

**Comment by ncrocfer** [comment]
This seems related to a new release of the `importlib-metadata` package in Celery requirements: https://github.com/celery/celery/issues/7783

We'll upgrade the Dockerfile to use Python 3.8 as proposed by @therob89

**Comment by hugohlr** [comment]
It's works now, thanks @therob89  ! Hope that will help somebody else ;)
