### ISSUE TITLE
Celery Worker - Error 111 connecting to 127.0.0.1:6379. Connection refused

### ISSUE THREAD

**Issue by jheeree** [opencve/opencve#258]
Hello.
I am currently having this problem with the celery worker, which does not allow to correctly update the CVE notification afterwards.
This is happening on Docker platform.

## Steps to Reproduce the Problem

  - docker logs -f celery_worker
---
   ```
[2023-01-19 20:12:30,688: ERROR/ForkPoolWorker-1] Task CVE_UPDATES[3021d442-7152-4841-992a-8671a58b6328] raised unexpected: ConnectionError('Error 111 connecting to 127.0.0.1:6379. Connection refused.')
Traceback (most recent call last):
  File "/app/venv/lib/python3.8/site-packages/redis/connection.py", line 539, in connect
    sock = self._connect()
  File "/app/venv/lib/python3.8/site-packages/redis/connection.py", line 596, in _connect
    raise err
  File "/app/venv/lib/python3.8/site-packages/redis/connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/venv/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/opencve/tasks/__init__.py", line 47, in cve_updates
    acquired = Lock(r, "cve_updates_lock", timeout=3600 * 12, blocking=False).acquire()
  File "/app/venv/lib/python3.8/site-packages/redis/lock.py", line 182, in acquire
    if self.do_acquire(token):
  File "/app/venv/lib/python3.8/site-packages/redis/lock.py", line 197, in do_acquire
    if self.redis.set(self.name, token, nx=True, px=timeout):
  File "/app/venv/lib/python3.8/site-packages/redis/client.py", line 1519, in set
    return self.execute_command('SET', *pieces)
  File "/app/venv/lib/python3.8/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/app/venv/lib/python3.8/site-packages/redis/connection.py", line 1073, in get_connection
    connection.connect()
  File "/app/venv/lib/python3.8/site-packages/redis/connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

```
## Specifications

  - OpenCVE version: v1.4.0
  - Python version: 3.8
  - Platform: Docker

**Comment by ncrocfer** [comment]
We can see in the error that the Celery worker can't connect to the Redis, so it's probably down.
Try to restart it.

**Comment by itsek** [comment]
have the same issue, here is the log:

```
/app/venv/lib/python3.8/site-packages/celery/platforms.py:800: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
[2023-02-20 08:40:29,681: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-02-20 08:40:29,688: INFO/MainProcess] mingle: searching for neighbors
[2023-02-20 08:40:30,703: INFO/MainProcess] mingle: all alone
[2023-02-20 08:40:30,714: INFO/MainProcess] celery@open-cve-celery-worker-f6b9f979b-8t2x9 ready.
[2023-02-20 08:55:18,111: INFO/MainProcess] Received task: CVE_UPDATES[06d19707-1135-4f9b-a470-fd5477a4cc43]
/app/venv/lib/python3.8/site-packages/celery/platforms.py:800: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
[2023-02-20 08:55:18,119: ERROR/ForkPoolWorker-1] Task CVE_UPDATES[06d19707-1135-4f9b-a470-fd5477a4cc43] raised unexpected: ConnectionError('Error 111 connecting to 127.0.0.1:6379. Connection refused.')
Traceback (most recent call last):
  File "/app/venv/lib/python3.8/site-packages/redis/connection.py", line 539, in connect
    sock = self._connect()
  File "/app/venv/lib/python3.8/site-packages/redis/connection.py", line 596, in _connect
    raise err
  File "/app/venv/lib/python3.8/site-packages/redis/connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/venv/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/opencve/tasks/__init__.py", line 47, in cve_updates
    acquired = Lock(r, "cve_updates_lock", timeout=3600 * 12, blocking=False).acquire()
  File "/app/venv/lib/python3.8/site-packages/redis/lock.py", line 182, in acquire
    if self.do_acquire(token):
  File "/app/venv/lib/python3.8/site-packages/redis/lock.py", line 197, in do_acquire
    if self.redis.set(self.name, token, nx=True, px=timeout):
  File "/app/venv/lib/python3.8/site-packages/redis/client.py", line 1519, in set
    return self.execute_command('SET', *pieces)
  File "/app/venv/lib/python3.8/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/app/venv/lib/python3.8/site-packages/redis/connection.py", line 1073, in get_connection
    connection.connect()
  File "/app/venv/lib/python3.8/site-packages/redis/connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
```

redis is running and accepting connections, see log entry at the start with 
```Connected to redis://redis:6379/0```
but then for some reason it tries to connect to 127.0.0.1:6379 - which is weird, since the conf file contains this:
```
celery_broker_url = redis://redis:6379/0
celery_result_backend = redis://redis:6379/1
celery_lock_url = redis://redis:6379/2
```

**Comment by itsek** [comment]
actually, before it looked like this and produced the error:
```
celery_broker_url = redis://redis:6379/0
celery_result_backend = redis://redis:6379/1
```

after adding the celery_lock_url parameter, it started working:
```
celery_broker_url = redis://redis:6379/0
celery_result_backend = redis://redis:6379/1
celery_lock_url = redis://redis:6379/2
```

**Comment by ncrocfer** [comment]
Ok I see, so it's normal yes. If you forgot to update your `opencve.cfg` after upgrading OpenCVE the code fallbacks on `127.0.0.1:6379` for the `celery_lock_url` option:

https://github.com/opencve/opencve/blob/fde6e7e1081471b8e2e928cc652ac907a0a7d6ea/opencve/settings.py#L69

You can read the changelog to check the new parameters: https://github.com/opencve/opencve/releases/tag/v1.4.0

**Comment by jheeree** [comment]
It worked! The problem was occurring due to the missing value in `celery_lock_url`.
Now everything works perfectly.
Thank you very much.
