### ISSUE TITLE
Attribute Error caused by old session cookie on new setup

### ISSUE THREAD

**Issue by jzelina** [opencve/opencve#259]
## Expected Behavior

OpenCVE webpage is load without errors, even if a browser use an old invalid session cookie.

## Actual Behavior

In K8s or docker it is not unlikely, that the deployment is removed and deployed again from the same source.
In this scenario i did delete OpenCVE including all resources and deployed it again. 

When opening the OpenCVE page with a session cookie from a former deployment of OpenCVE,
the webserver reply with 500 Internal Server Error and the following log message:
```

[2023-01-20 13:58:46,696] ERROR in app: Exception on /cve [GET]
Traceback (most recent call last):
  File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/venv/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/venv/lib/python3.8/site-packages/opencve/views/cves.py", line 23, in cves
    if current_user.is_authenticated:
  File "/app/venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/app/venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/app/venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/app/venv/lib/python3.8/site-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/app/venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "/app/venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "/app/venv/lib/python3.8/site-packages/flask_user/user_manager.py", line 130, in load_user_by_user_token
    user = self.db_manager.UserClass.get_user_by_token(user_token)
  File "/app/venv/lib/python3.8/site-packages/flask_user/user_mixin.py", line 52, in get_user_by_token
    user_password = '' if user_manager.USER_ENABLE_AUTH0 else user.password[-8:]
AttributeError: 'NoneType' object has no attribute 'password'
192.168.1.16 - - [20/Jan/2023:13:58:46 +0000] "GET /cve HTTP/1.1" 500 290 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
```

## Steps to Reproduce the Problem

  - Setup OpenCVE from scratch +  login user via browser
  - Delete the deployment (everything)
  - setup OpenCVE from scratch (same flask secret etc.) and browse the webpage
  -- as long my browser use the former session cookie opencve respond with internal error.
  -- once my session cookie is removed from the browser or i use a new browser the webpage works.

## Specifications

  - OpenCVE version: 1.4.0
  - Python version: 3.8
  - Platform: K8s / docker

**Comment by ncrocfer** [comment]
I think this problem is raised by the underlying users package I use in the current version of OpenCVE (Flask-User). I will not try to fix it because I work on the new version based on Django, this problem will be fixed in it.

**Comment by ncrocfer** [comment]
Closing this issue as OpenCVE is now based on Django for the webserver component, this bug is no more present.
