### ISSUE TITLE
New install (docker) - not updating

### ISSUE THREAD

**Issue by ekrichbaum** [opencve/opencve#260]
## Expected Behavior
celery? should update data.

## Actual Behavior
admin gui shows no updates since import

## Steps to Reproduce the Problem
pieces all seem to be running and accessible (gui:8000 works, admin tab works, api works, so db uri is correct in conf.

celery_worker logs  logs  have errors.
psycopg2.OperationalError: could not translate host name "thisismypassword" to address: Name or service not known
and
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "thisismypassword" to address: Name or service not known

This is why this is not updating at this point.
[2023-01-20 16:33:12,849: INFO/ForkPoolWorker-1] HANDLE_EVENTS[9cadfb3d-7791-415b-a1b5-fd586f562ce0]: Checking for new events...
[2023-01-20 16:33:12,850: INFO/ForkPoolWorker-1] HANDLE_EVENTS[9cadfb3d-7791-415b-a1b5-fd586f562ce0]: Downloading https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta...
[2023-01-20 16:33:12,985: INFO/MainProcess] Received task: RELEASE_LOCK[42ce49b9-99cb-4e04-b463-75c4c44e7e85]  
[2023-01-20 16:33:12,984: ERROR/ForkPoolWorker-1] Task HANDLE_EVENTS[9cadfb3d-7791-415b-a1b5-fd586f562ce0] raised unexpected: OperationalError('(psycopg2.OperationalError) could not translate host name "thisismypassword" to address: Name or service not known\n')

```
Traceback (most recent call last):
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 354, in connect
    return _ConnectionFairy._checkout(self)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 751, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 483, in checkout
    rec = pool._do_get()
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 138, in _do_get
    self._dec_overflow()
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 135, in _do_get
    return self._create_connection()
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 299, in _create_connection
    return _ConnectionRecord(self)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 428, in __init__
    self.__connect(first_connect_check=True)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 630, in __connect
    connection = pool._invoke_creator(self)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/app/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "thisismypassword" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/venv/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/opencve/tasks/events.py", line 94, in handle_events
    current_sum, new_sum = has_changed()
  File "/app/venv/lib/python3.8/site-packages/opencve/tasks/events.py", line 31, in has_changed
    last_nvd256 = Meta.query.filter_by(name="nvd_last_sha256").first()
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3215, in first
    ret = list(self[0:1])
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3007, in __getitem__
    return list(res)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3338, in _execute_and_instances
    conn = self._get_bind_args(
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3353, in _get_bind_args
    return fn(
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3332, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1120, in connection
    return self._connection_for_bind(
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1128, in _connection_for_bind
    return self.transaction._connection_for_bind(
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 430, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2226, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2265, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1536, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 354, in connect
    return _ConnectionFairy._checkout(self)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 751, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 483, in checkout
    rec = pool._do_get()
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 138, in _do_get
    self._dec_overflow()
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 135, in _do_get
    return self._create_connection()
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 299, in _create_connection
    return _ConnectionRecord(self)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 428, in __init__
    self.__connect(first_connect_check=True)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 630, in __connect
    connection = pool._invoke_creator(self)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/app/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "thisismypassword" to address: Name or service not known
```

  - 
  - 
  - 

## Specifications

  - OpenCVE version: 1.4.0 docker
  - Python version: Python 3.8.16
  - Platform: debian 11

**Comment by ncrocfer** [comment]
I don't understand why the hostname of your PostgreSQL URI is talking about a password...

How did you install OpenCVE and what commands did you launched? (without the actions you did I could not help you ;))

**Comment by ekrichbaum** [comment]
Followed the docker instructions. I'm not real familiar with docker but wasn't getting anywhere without it because of the jsmin issue.

Eventually, the system did start updating (unclear on what the schedule or mechanism within does that portion, so this was probably unrelated to updating specifically.
