### ISSUE TITLE
celery_worker reports Can't reconnect until invalid transaction is rolled back

### ISSUE THREAD

**Issue by security101** [opencve/opencve#261]
## Expected Behavior

When HANDLE_ALERTS is processing and an Error like sqlalchemy.exc.InvalidRequestError aka "Can't reconnect until invalid transaction is rolled back" is reported an automatic rollback is performed to cure this issue during operations. 

## Actual Behavior

celery_beat    | [2023-02-04 14:36:55,182: INFO/MainProcess] Scheduler: Sending due task cve-updates-15-mn (CVE_UPDATES)
celery_worker  | [2023-02-04 14:36:55,188: INFO/MainProcess] Received task: CVE_UPDATES[23773b83-2d22-480c-be1f-a48ae737b4e4]  
celery_worker  | [2023-02-04 14:36:55,199: INFO/MainProcess] Received task: HANDLE_EVENTS[41c45577-1a55-4818-86dc-11d5415e9c86]  
celery_worker  | [2023-02-04 14:36:55,200: INFO/ForkPoolWorker-7] Task CVE_UPDATES[23773b83-2d22-480c-be1f-a48ae737b4e4] succeeded in 0.00930950790643692s: None
celery_worker  | [2023-02-04 14:36:55,201: INFO/ForkPoolWorker-1] HANDLE_EVENTS[41c45577-1a55-4818-86dc-11d5415e9c86]: Checking for new events...
celery_worker  | [2023-02-04 14:36:55,201: INFO/ForkPoolWorker-1] HANDLE_EVENTS[41c45577-1a55-4818-86dc-11d5415e9c86]: Downloading https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta...
celery_worker  | [2023-02-04 14:36:55,548: INFO/ForkPoolWorker-1] HANDLE_EVENTS[41c45577-1a55-4818-86dc-11d5415e9c86]: DB is up to date.
celery_worker  | [2023-02-04 14:36:55,553: INFO/ForkPoolWorker-1] Task HANDLE_EVENTS[41c45577-1a55-4818-86dc-11d5415e9c86] succeeded in 0.3526729419827461s: None

celery_worker  | [2023-02-04 14:36:55,554: INFO/MainProcess] Received task: HANDLE_ALERTS[c26b1bac-3b05-4290-8858-d93ad1fa2611]  
celery_worker  | [2023-02-04 14:36:55,556: INFO/ForkPoolWorker-3] HANDLE_ALERTS[c26b1bac-3b05-4290-8858-d93ad1fa2611]: Checking for new alerts...
celery_worker  | [2023-02-04 14:36:55,566: INFO/MainProcess] Received task: RELEASE_LOCK[eec5a197-1723-4b32-a2ac-bdcfc1984a98]  
celery_worker  | [2023-02-04 14:36:55,566: ERROR/ForkPoolWorker-3] Task HANDLE_ALERTS[c26b1bac-3b05-4290-8858-d93ad1fa2611] raised unexpected: StatementError("(sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back")
celery_worker  | Traceback (most recent call last):
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1177, in _execute_context
celery_worker  |     conn = self._revalidate_connection()
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 462, in _revalidate_connection
celery_worker  |     raise exc.InvalidRequestError(
celery_worker  | sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back
celery_worker  | 
celery_worker  | The above exception was the direct cause of the following exception:
celery_worker  | 
celery_worker  | Traceback (most recent call last):
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
celery_worker  |     R = retval = fun(*args, **kwargs)
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
celery_worker  |     return self.run(*args, **kwargs)
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/opencve/tasks/alerts.py", line 44, in handle_alerts
celery_worker  |     cves = Cve.query.filter(Cve.events.any(Event.review == False)).all()
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3161, in all
celery_worker  |     return list(self)
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
celery_worker  |     return self._execute_and_instances(context)
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
celery_worker  |     result = conn.execute(querycontext.statement, self._params)
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 988, in execute
celery_worker  |     return meth(self, multiparams, params)
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
celery_worker  |     return connection._execute_clauseelement(self, multiparams, params)
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
celery_worker  |     ret = self._execute_context(
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1181, in _execute_context
celery_worker  |     self._handle_dbapi_exception(
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
celery_worker  |     util.raise_from_cause(sqlalchemy_exception, exc_info)
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
celery_worker  |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
celery_worker  |     raise value.with_traceback(tb)
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1177, in _execute_context
celery_worker  |     conn = self._revalidate_connection()
celery_worker  |   File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 462, in _revalidate_connection
celery_worker  |     raise exc.InvalidRequestError(
celery_worker  | sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
celery_worker  | [SQL: SELECT cves.id AS cves_id, cves.created_at AS cves_created_at, cves.updated_at AS cves_updated_at, cves.cve_id AS cves_cve_id, cves.json AS cves_json, cves.vendors AS cves_vendors, cves.cwes AS cves_cwes, cves.summary AS cves_summary, cves.cvss2 AS cves_cvss2, cves.cvss3 AS cves_cvss3 
celery_worker  | FROM cves 
celery_worker  | WHERE EXISTS (SELECT 1 
celery_worker  | FROM events 
celery_worker  | WHERE cves.id = events.cve_id AND events.review = false)]
celery_worker  | [parameters: [{}]]
celery_worker  | [2023-02-04 14:36:55,573: INFO/ForkPoolWorker-5] Task RELEASE_LOCK[eec5a197-1723-4b32-a2ac-bdcfc1984a98] succeeded in 0.0047171153128147125s: None

## Steps to Reproduce the Problem

  - Occured during normal operations to I can only refer to the logs means docker-compose logs -f 
  -   - 
  - 

## Specifications

  - OpenCVE version: 1.4.0 
  - Python version: python:3.8
  - Platform: Docker Container

**Comment by ncrocfer** [comment]
Hi,

It seems to be related to this issue: https://github.com/opencve/opencve/issues/57

Can you connect on the `celery_worker` container and execute `db.session.rollback`?

**Comment by Thangart** [comment]
I seem to have the same problem. 
how can i execute the db.session.rollback on the celery_worker? is there a any documentation on this step?

**Comment by ncrocfer** [comment]
Check here: https://github.com/opencve/opencve/issues/84#issuecomment-808929259

**Comment by Thangart** [comment]
Hi Nicolas,

Thank you for the link! I tried the db rollback action but the same error popped up on the next update request.
The SQL query that gets stuck is slightly different from the OP.

 sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
opencve_celery_worker.1.yupn9y1ornhg@...    | [SQL: SELECT metas.id AS metas_id, metas.created_at AS metas_created_at, metas.updated_at AS metas_updated_at, metas.name AS metas_name, metas.value AS metas_value
opencve_celery_worker.1.yupn9y1ornhg@...    | FROM metas
opencve_celery_worker.1.yupn9y1ornhg@...   | WHERE metas.name = %(name_1)s
opencve_celery_worker.1.yupn9y1ornhg@...  |  LIMIT %(param_1)s]

I'm running in a docker swarm environment and have recreated the service multiple times and allways got back to this specific set of errors after a couple of hours of operation. Even destroying the database and reseeding it didnt solve it for me.
The funny thing is that after i delete the stack and recreate it it works fine for the first couple of updates before spiraling back into this loop.

Should i create a new issue for this or can i keep going on in this one?

**Comment by ncrocfer** [comment]
We use Docker for the Opencve.io website and we don't have this error. The only diff I see is your swarm environment, maybe the probem comes from there?

Unfortunately I'm not comfortable with docker swarm, so if someone else can help @Thangart thanks in advance 👍

**Comment by schenklklopfer** [comment]
We use Docker Swarm as well, had the Issue described above.
The fix with `db.session.rollback` worked for us!
(As described here: https://github.com/opencve/opencve/issues/84#issuecomment-808929259)

**Comment by schenklklopfer** [comment]
Recently the same error as in https://github.com/opencve/opencve/issues/261#issuecomment-1442932190 appeared, than tried `db.session.rollback` without any effect.

Restarted both celery Container (celery_worker and celery_beat), than the updates are working again.

**Comment by dr-yd** [comment]
We have the same recurring issue, running in Docker Swarm as well. Furthermore, when connecting to OpenCVE for the first time in a while (such as first thing Monday), we'll get this:

```
[2024-09-30 08:32:59,237] ERROR in app: Exception on /cve [GET]
Traceback (most recent call last):
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

There are no outgoing packets to Postgres, and no incoming ones on the Postgres server, not even a SYN. From the second request, everything starts to work again as normal. I assume that this is some problem with the SQLAlchemy pool going stale or even an L4 problem, but I can't find a way to tweak anything on the Python side, the application doesn't even have a setting for logging level.Ttogether with the fact that it's been frozen for almost a year, it looks like this project isn't worth the hassle of trying to get it to work correctly.

**Comment by schenklklopfer** [comment]
> Hello @schenklklopfer / @dr-yd - I am interested how did you setup the v2 on swarm mode?

I've tried it but it is nearly impossible.
The provided docker-compose.yml is incredible complicated, I see almost no chance that this will work in swarm, as long as they do not supoort it officially.

**Comment by ncrocfer** [comment]
> The provided docker-compose.yml is incredible complicated

@schenklklopfer what's your advice to simplify it?

**Comment by schenklklopfer** [comment]
> > The provided docker-compose.yml is incredible complicated
> 
> @schenklklopfer what's your advice to simplify it?

I talk about the v2 file: https://github.com/opencve/opencve/blob/v2/docker/docker-compose.yaml

Basically: Keep it simple.
The file uses almost everything possible in YAML and docker-compose.
Of course this is elegant and nice to have, but this makes it almost impossible to convert it to a different environment.

Just a few points to simplify it:

- "build:" There is no need to build the image inside the compose.yml - this is a thing Docker Swarm cannot do - build can be done outside as well
- "depends_on:" clever compose stuff, but impossible in Docker Swarm too, so the application should be aware of f.e. a database that might takes a few more moments to startup - this shouln't be offloaded to docker, the application can do this way better
- "volumes:" One cannot use volumes in Docker Swarm Clusters, one need always use mounted filesystems, that are located on a replicated local filesystem

**Comment by ncrocfer** [comment]
@schenklklopfer 

Thank you for your feedback.

From what I can tell, many of the challenges you pointed out seem related specifically to Docker Swarm.

Compared to other `docker-compose.yml` files, the OpenCVE setup strikes me as relatively simple, with a limited number of containers and volumes. However, it could be that the complexity you observe is tied more closely to migrating to Docker Swarm than to the inherent complexity of this compose.yml itself 😉 

Additionally, implementing changes such as removing `depends_on` or skipping volumes would indeed enhance Swarm compatibility, but it might also reduce accessibility for users who want a quick setup with Docker Compose alone.

If you have any suggestions on how we might achieve both a simple Docker Compose setup and Swarm compatibility, we’d be very interested in hearing them 👍

**Comment by ncrocfer** [comment]
Closing this issue as original answer was dedicated to v1.  Feel free to reopen another clearer one if needed.
