### ISSUE TITLE
Unable to start webserver [ERROR] Exception in worker process

### ISSUE THREAD

**Issue by BillyMyIT** [opencve/opencve#280]
Hi all,

My opencve was working fine but it's a VM and i needed to restart host.
Now the opencve is not working. I tried :
**opencve webserver 0.0.0.0:8000**

`[2023-05-03 11:45:05 +0000] [382622] [INFO] Starting gunicorn 20.0.4
[2023-05-03 11:45:05 +0000] [382622] [INFO] Listening at: http://127.0.0.1:8000 (382622)
[2023-05-03 11:45:05 +0000] [382622] [INFO] Using worker: sync
[2023-05-03 11:45:05 +0000] [382627] [INFO] Booting worker with pid: 382627
[2023-05-03 11:45:05 +0000] [382627] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/billyit/.local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/billyit/.local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/billyit/.local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/billyit/.local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/billyit/.local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/billyit/.local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/billyit/.local/lib/python3.9/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named '0'
[2023-05-03 11:45:05 +0000] [382627] [INFO] Worker exiting (pid: 382627)
[2023-05-03 11:45:06 +0000] [382622] [INFO] Shutting down: Master
[2023-05-03 11:45:06 +0000] [382622] [INFO] Reason: Worker failed to boot.
`
Can't find a solution about it for now, can you help ?

**Comment by ncrocfer** [comment]
Your forgot the `-b` (https://docs.opencve.io/commands/#webserver).

**Comment by BillyMyIT** [comment]
> Your forgot the `-b` (https://docs.opencve.io/commands/#webserver).

Correct :)
My bad... It was long time ago that i started it and in my history i didn't have the "-b"... 

Thanks you !!
