### ISSUE TITLE
import-data not working

### ISSUE THREAD

**Issue by denmaddog** [opencve/opencve#288]
## Running `docker exec -it webserver opencve import-data` ends up with an error:
```
docker exec -it webserver opencve import-data
This command will import initial data in your database. Do you want to continue ? [y/N]: y
#####################
Importing CWE list...
#####################
[*] Downloading https://cwe.mitre.org/data/xml/cwec_latest.xml.zip... (done in 1.951s).
[*] Parsing cwes... (done in 2.27s).
[*] Creating mappings... (done in 0.029s).
[*] Inserting CWE... (done in 0.268s).
[*] 1367 CWE imported.
######################
Importing CVE for 2002
######################
[*] Downloading https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2002.json.gz... (done in 0.719s).
[*] Parsing JSON elements... (done in 0.615s).
[*] Creating model objects... (done in 1.481s).
[*] Inserting CVE... (done in 8.987s).
[*] 6769 CVE imported.
######################
Importing CVE for 2003
######################
[*] Downloading https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2003.json.gz... (done in 0.221s).
[*] Parsing JSON elements...Traceback (most recent call last):
  File "/app/venv/bin/opencve", line 8, in <module>
    sys.exit(cli())
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/opencve/commands/__init__.py", line 39, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/opencve/commands/imports/__init__.py", line 41, in import_data
    vendors = cve.run()
  File "/app/venv/lib/python3.8/site-packages/opencve/commands/imports/cve.py", line 45, in run
    raw = gzip.GzipFile(fileobj=BytesIO(resp)).read()
  File "/usr/local/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/usr/local/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/usr/local/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'<h')
```
Running same command after that returns:
```
docker exec -it webserver opencve import-data
[*] Import already done.
```
But when going to http://localhost:8000/vendors?search=
there is nothing found of Vendors and Products to subscribe to.

## Steps to Reproduce the Problem

`  - docker exec -it webserver opencve import-data`

## Specifications

  - OpenCVE version: opencve:1.4.1
  - Python version: Python 3.8.17
  - Platform: docker-compose version 1.25.0
![Screenshot_20230705_144811](https://github.com/opencve/opencve/assets/13506607/6a80c30e-b912-4e51-b46c-d0ceec9d025e)

**Comment by denmaddog** [comment]
Increasing RAM helped.
