### ISSUE TITLE
How to receive email notifications

### ISSUE THREAD

**Issue by denmaddog** [opencve/opencve#290]
Hello,

I'm running OpenCVE with Docker-compose as per documentation. I've subscribed to some vendors and products.
I have setup my notifications to alert upon any change.
I also see some reports being generated.
The problem is that I am not receiving any email alerts.

Can you please help?

Zeljko

**Comment by denmaddog** [comment]
Update:
In logs I see error saying to check SMTP SERVER and SMTP PORT.

In config I have:

```
[mail]
; Choices are 'smtp' or 'sendmail'
email_adapter = smtp

; The 'From' field of the sent emails
email_from = no-reply-opencve@example.com

; Configuration to set up SMTP mails.
smtp_server = 10.12.10.68
smtp_port = 25
smtp_use_tls = False
smtp_use_ssl = False
smtp_username = <your_username>
smtp_password = <your_password>

```
The smtp_server and smtp_port are IP and port of another instance with Postfix configured. I can telnet from OpenCVE instance to it. It works as SMTP for other services without an issue.

Can you please help and let me know what am I doing wrong?

BTW, what is the difference between smtp and sendmail email agent?

Thanks,

Zeljko

**Comment by denmaddog** [comment]
When I try to update user password I get:

```
webserver        | [2023-07-07 14:34:46,625] ERROR in app: Exception on /account/password [POST]
webserver        | Traceback (most recent call last):
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask_user/email_adapters/smtp_email_adapter.py", line 64, in send_email_message
webserver        |     self.mail.send(message)
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask_mail.py", line 491, in send
webserver        |     with self.connect() as connection:
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask_mail.py", line 144, in __enter__
webserver        |     self.host = self.configure_host()
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask_mail.py", line 165, in configure_host
webserver        |     host.login(self.mail.username, self.mail.password)
webserver        |   File "/usr/local/lib/python3.8/smtplib.py", line 714, in login
webserver        |     raise SMTPNotSupportedError(
webserver        | smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
webserver        | 
webserver        | During handling of the above exception, another exception occurred:
webserver        | 
webserver        | Traceback (most recent call last):
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
webserver        |     response = self.full_dispatch_request()
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
webserver        |     rv = self.handle_user_exception(e)
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
webserver        |     return original_handler(e)
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
webserver        |     reraise(exc_type, exc_value, tb)
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
webserver        |     raise value
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
webserver        |     rv = self.dispatch_request()
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
webserver        |     return self.view_functions[rule.endpoint](**req.view_args)
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask_user/user_manager.py", line 386, in change_password_stub
webserver        |     return self.change_password_view()
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask_user/decorators.py", line 58, in decorator
webserver        |     return view_function(*args, **kwargs)
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask_user/user_manager__views.py", line 107, in change_password_view
webserver        |     self.email_manager.send_password_changed_email(current_user)
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask_user/email_manager.py", line 72, in send_password_changed_email
webserver        |     self._render_and_send_email(
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask_user/email_manager.py", line 191, in _render_and_send_email
webserver        |     self.user_manager.email_adapter.send_email_message(
webserver        |   File "/app/venv/lib/python3.8/site-packages/flask_user/email_adapters/smtp_email_adapter.py", line 68, in send_email_message
webserver        |     raise EmailError('SMTP Connection error: Check your MAIL_SERVER and MAIL_PORT settings.')
webserver        | flask_user.EmailError: SMTP Connection error: Check your MAIL_SERVER and MAIL_PORT settings.
```

**Comment by ncrocfer** [comment]
It seems to be a problem related to your SMTP configuration, maybe bad credentials? Unfortunately I'm not an expert of SMTP.

**Comment by ncrocfer** [comment]
OpenCVE architecture has been updated, it now uses Django & Airflow.
You can use this doc to check & configure your SMTP configuration: https://docs.opencve.io/guides/smtp_configuration/
