### ISSUE TITLE
UndefinedTable: relation "cves" does not exist

### ISSUE THREAD

**Issue by Jderach** [opencve/opencve#305]
Hello, 

When importing CVEs, I get an error telling me that the "cves" relationship does not exist.

`root@vmsopencve:~/opencve-docker# docker exec -it webserver opencve import-data
Traceback (most recent call last):
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "cves" does not exist
LINE 2: FROM cves
             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/venv/bin/opencve", line 8, in <module>
    sys.exit(cli())
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/opencve/commands/__init__.py", line 39, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/opencve/commands/imports/__init__.py", line 23, in import_data
    if Cve.query.first():
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3215, in first
    ret = list(self[0:1])
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3007, in __getitem__
    return list(res)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    ret = self._execute_context(
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self._handle_dbapi_exception(
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "cves" does not exist
LINE 2: FROM cves
             ^

[SQL: SELECT cves.id AS cves_id, cves.created_at AS cves_created_at, cves.updated_at AS cves_updated_at, cves.cve_id AS cves_cve_id, cves.json AS cves_json, cves.vendors AS cves_vendors, cves.cwes AS cves_cwes, cves.summary AS cves_summary, cves.cvss2 AS cves_cvss2, cves.cvss3 AS cves_cvss3
FROM cves
 LIMIT %(param_1)s]
[parameters: {'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)
`

## Specifications

OpenCVE version: 1.4.1
Python version: 3.8.10
Platform: Ubuntu 20.04

**Comment by ncrocfer** [comment]
Hello,

The message is pretty clear:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "cves" does not exist
```

The `cves` table doesn't exist, did you create the tables before importing the data? The documentation is here: https://docs.opencve.io/installation/docker/#initialize-the-database

**Comment by ncrocfer** [comment]
Closing this issue as it has been inactive for a long time.
