### ISSUE TITLE
Airflow task fails with 'Repository seems empty or broken' error for 'fetch_redhat'

### ISSUE THREAD

**Issue by HosneMubarak** [opencve/opencve#380]
## Expected Behavior:
The Airflow task "cves.fetch_redhat" should successfully fetch data from the Red Hat repository.

## Actual Behavior:
The task failed with the following error:
[2024-05-14, 11:00:02 UTC] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/includes/operators/fetch_operator.py", line 13, in execute
    raise AirflowException(f"Repository {repo_path} seems empty or broken")
airflow.exceptions.AirflowException: Repository /home/airflow/repositories/***-redhat seems empty or broken
[2024-05-14, 11:00:02 UTC] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=***, task_id=cves.fetch_redhat, execution_date=20240514T100000, start_date=20240514T110002, end_date=20240514T110002
[2024-05-14, 11:00:02 UTC] {standard_task_runner.py:107} ERROR - Failed to execute job 49 for task cves.fetch_redhat (Repository /home/airflow/repositories/***-redhat seems empty or broken; 77)
[2024-05-14, 11:00:02 UTC] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-14, 11:00:02 UTC] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check

## Steps to Reproduce the Problem
- Trigger the Airflow DAG containing the task "cves.fetch_redhat".
- Observe the task failure due to the empty or broken repository.

## Specifications
- OpenCVE version: [Please specify]
- Python version: [Please specify]
- Platform: [Please specify]

## Screenshots (optional)
![Screenshot 2024-05-14 234014](https://github.com/opencve/opencve/assets/45841520/419bf7e1-7136-4b6a-99a2-8f578479de97)

**Comment by ncrocfer** [comment]
Hi @HosneMubarak ,

Apparently you tried the `v2` branch but we didn't announced it yet, we're still developing some features on it so it's normal to see this kind of errors ^^

We'll make an announce on the README when it will be a "stable beta" :wink:

**Comment by HosneMubarak** [comment]
Thanks for letting me know about the v2 branch! It's great to hear about the ongoing development. But for one of my project, I want to use this Django version.  Do you have any suggestions on what we should do next?
