### ISSUE TITLE
No more CVEs appear in OpenCVE

### ISSUE THREAD

**Issue by mael-actia** [opencve/opencve#413]
## Expected Behavior

New CVEs appear in the OpenCVE tool

## Actual Behavior

Since August 02, 2024, no new CVEs have appeared on either the dashboard or the project dashboards. 

![dashboard_opencve](https://github.com/user-attachments/assets/4c958586-352e-4672-a907-5ebf546f9219)

## Steps to Reproduce the Problem

I can't reproduce the problem because the docker containers are working, the website is displayed correctly but no new CVE appears.

However, I connected to the airflow-worker container and went to the log directory 
```bash airflow@6079377851f9:/opt/airflow/logs/dag_id=opencve/run_id=scheduled__2024-09-09T00:00:00+00:00/task_id=cves.pull_nvd' ```
And I have the following logs:

```bash
airflow@6079377851f9:/opt/airflow/logs/dag_id=opencve/run_id=scheduled__2024-09-09T00:00:00+00:00/task_id=cves.pull_nvd$ cat attempt\=1.log 
[2024-09-09T01:00:01.323+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: opencve.cves.pull_nvd scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-09-09T01:00:01.347+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: opencve.cves.pull_nvd scheduled__2024-09-09T00:00:00+00:00 [queued]>      
[2024-09-09T01:00:01.348+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-09T01:00:01.365+0000] {taskinstance.py:2191} INFO - Executing <Task(GitPullOperator): cves.pull_nvd> on 2024-09-09 00:00:00+00:00
[2024-09-09T01:00:01.370+0000] {standard_task_runner.py:60} INFO - Started process 235879 to run task
[2024-09-09T01:00:01.379+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '***', 'cves.pull_nvd', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '16103', '--raw', '--subdir', 'DAGS_FOLDER/***_dag.py', '--cfg-path', '/tmp/tmpy69pcrk3']
[2024-09-09T01:00:01.380+0000] {standard_task_runner.py:88} INFO - Job 16103: Subtask cves.pull_nvd
[2024-09-09T01:00:01.478+0000] {task_command.py:423} INFO - Running <TaskInstance: opencve.cves.pull_nvd scheduled__2024-09-09T00:00:00+00:00 [running]> on host 6079377851f9
[2024-09-09T01:00:01.634+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='***' AIRFLOW_CTX_TASK_ID='cves.pull_nvd' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-09-09T01:00:01.658+0000] {fetch_operator.py:23} INFO - Local HEAD is f03426961ebbf4c8db20d9865c25dd2d63118d6d
[2024-09-09T01:00:01.658+0000] {fetch_operator.py:24} INFO - Pulling last changes from /home/airflow/repositories/***-nvd...
[2024-09-09T01:00:02.244+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/includes/operators/fetch_operator.py", line 25, in execute
    repo.remotes.origin.pull("main")
  File "/home/airflow/.local/lib/python3.11/site-packages/git/remote.py", line 1054, in pull
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/home/airflow/.local/lib/python3.11/site-packages/git/cmd.py", line 600, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v -- origin main
  stderr: 'fatal: Need to specify how to reconcile divergent branches.'
[2024-09-09T01:00:02.267+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=***, task_id=cves.pull_nvd, execution_date=20240909T000000, start_date=20240909T010001, end_date=20240909T010002   
[2024-09-09T01:00:02.282+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16103 for task cves.pull_nvd (Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v -- origin main
  stderr: 'fatal: Need to specify how to reconcile divergent branches.'; 235879)
[2024-09-09T01:00:02.327+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-09T01:00:02.362+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
airflow@6079377851f9:/opt/airflow/logs/dag_id=opencve/run_id=scheduled__2024-09-09T00:00:00+00:00/task_id=cves.pull_nvd$
```

The same applies to the log file in the ```bash task_id=cves.pull_kb directory.```

```bash
airflow@6079377851f9:/opt/airflow/logs/dag_id=opencve/run_id=scheduled__2024-09-09T00:00:00+00:00/task_id=cves.pull_kb$ cat attempt\=1.log 
[2024-09-09T01:00:01.172+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: opencve.cves.pull_kb scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-09-09T01:00:01.187+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: opencve.cves.pull_kb scheduled__2024-09-09T00:00:00+00:00 [queued]>       
[2024-09-09T01:00:01.187+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-09T01:00:01.214+0000] {taskinstance.py:2191} INFO - Executing <Task(GitPullOperator): cves.pull_kb> on 2024-09-09 00:00:00+00:00
[2024-09-09T01:00:01.217+0000] {standard_task_runner.py:60} INFO - Started process 235877 to run task
[2024-09-09T01:00:01.228+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '***', 'cves.pull_kb', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '16101', '--raw', '--subdir', 'DAGS_FOLDER/***_dag.py', '--cfg-path', '/tmp/tmpj3mdfucu']
[2024-09-09T01:00:01.230+0000] {standard_task_runner.py:88} INFO - Job 16101: Subtask cves.pull_kb
[2024-09-09T01:00:01.341+0000] {task_command.py:423} INFO - Running <TaskInstance: opencve.cves.pull_kb scheduled__2024-09-09T00:00:00+00:00 [running]> on host 6079377851f9
[2024-09-09T01:00:01.520+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='***' AIRFLOW_CTX_TASK_ID='cves.pull_kb' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-09-09T01:00:01.539+0000] {fetch_operator.py:23} INFO - Local HEAD is 144d0125d0ee76c0d9e3a945010f57f33cd3e89a
[2024-09-09T01:00:01.540+0000] {fetch_operator.py:24} INFO - Pulling last changes from /home/airflow/repositories/***-kb...
[2024-09-09T01:00:02.299+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/includes/operators/fetch_operator.py", line 25, in execute
    repo.remotes.origin.pull("main")
  File "/home/airflow/.local/lib/python3.11/site-packages/git/remote.py", line 1054, in pull
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/home/airflow/.local/lib/python3.11/site-packages/git/cmd.py", line 600, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v -- origin main
  stderr: 'fatal: Need to specify how to reconcile divergent branches.'
[2024-09-09T01:00:02.315+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=***, task_id=cves.pull_kb, execution_date=20240909T000000, start_date=20240909T010001, end_date=20240909T010002    
[2024-09-09T01:00:02.328+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16101 for task cves.pull_kb (Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v -- origin main
  stderr: 'fatal: Need to specify how to reconcile divergent branches.'; 235877)
[2024-09-09T01:00:02.378+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-09T01:00:02.421+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
airflow@6079377851f9:/opt/airflow/logs/dag_id=opencve/run_id=scheduled__2024-09-09T00:00:00+00:00/task_id=cves.pull_kb$
```

## Specifications

  - OpenCVE version: OpenCVE v2
  - Python version: Python 3.11.9
  - Platform: Linux Debian 12.5

**Comment by ncrocfer** [comment]
Hello,

It looks like you’ve installed the `v2` branch of OpenCVE some time ago. Please note that during that period, the v2 was not yet stable, and we made significant changes, including a reset of the knowledge base (KB) in early August.

As a result, your instance is likely broken due to these changes.

Now that v2 is officially live and stable on https://www.opencve.io/, we won’t be making further resets to the KB. To get your instance working again, we recommend resetting your database and reinstalling OpenCVE from scratch.

We are currently working on a detailed installation and configuration guide for OpenCVE v2, which will be available soon to help you with the process.
