### ISSUE TITLE
celery worker report errors：“AttributeError: 'NoneType' object has no attribute 'value' ”

### ISSUE THREAD

**Issue by gitworldhero** [opencve/opencve#67]
Dear all，
    When I run the command：`opencve celery worker -l INFO  `
    **The program will report an error：**
 ```
    [tasks]
  . CVE_UPDATES
  . HANDLE_ALERTS
  . HANDLE_EVENTS
  . HANDLE_REPORTS

[2021-02-19 02:11:07,539: INFO/MainProcess] Connected to redis://127.0.0.1:6379/0
[2021-02-19 02:11:07,546: INFO/MainProcess] mingle: searching for neighbors
[2021-02-19 02:11:08,565: INFO/MainProcess] mingle: all alone
[2021-02-19 02:11:08,587: INFO/MainProcess] celery@kali ready.
[2021-02-19 02:23:50,383: INFO/MainProcess] Received task: CVE_UPDATES[43c9f1ee-fdcd-4bec-ac75-14355943fa47]  
[2021-02-19 02:23:50,415: INFO/MainProcess] Received task: HANDLE_EVENTS[889f5812-5cb5-454d-8555-def043db95a5]  
[2021-02-19 02:23:50,415: INFO/ForkPoolWorker-1] Task CVE_UPDATES[43c9f1ee-fdcd-4bec-ac75-14355943fa47] succeeded in 0.028891843001474626s: <AsyncResult: 7d980a92-c3dc-47b4-81df-a599a8324475>
[2021-02-19 02:23:50,418: INFO/ForkPoolWorker-2] HANDLE_EVENTS[889f5812-5cb5-454d-8555-def043db95a5]: Checking for new events...
[2021-02-19 02:23:50,419: INFO/ForkPoolWorker-2] HANDLE_EVENTS[889f5812-5cb5-454d-8555-def043db95a5]: Downloading https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta...
[2021-02-19 02:23:51,991: ERROR/ForkPoolWorker-2] Task HANDLE_EVENTS[889f5812-5cb5-454d-8555-def043db95a5] raised unexpected: AttributeError("'NoneType' object has no attribute 'value'")                                          
Traceback (most recent call last):                                                                                
  File "/home/kali/.local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task               
    R = retval = fun(*args, **kwargs)                                                                             
  File "/home/kali/.local/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__       
    return self.run(*args, **kwargs)                                                                              
  File "/home/kali/.local/lib/python3.8/site-packages/opencve/tasks/events.py", line 94, in handle_events         
    current_sum, new_sum = has_changed()                                                                          
  File "/home/kali/.local/lib/python3.8/site-packages/opencve/tasks/events.py", line 33, in has_changed           
    if nvd_sha256 != last_nvd256.value:                                                                           
AttributeError: 'NoneType' object has no attribute 'value'                     
```
It seems that this error will result in the failure to update the new CVE to the database

**Comment by ncrocfer** [comment]
It means `last_nvd256` is not populated.

It's done with the `import-data` command : https://github.com/opencve/opencve/blob/master/opencve/commands/imports/__init__.py#L46

Did you launch it ?

**Comment by A1oha** [comment]
> It means `last_nvd256` is not populated.
> 
> It's done with the `import-data` command : https://github.com/opencve/opencve/blob/master/opencve/commands/imports/__init__.py#L46
> 
> Did you launch it ?
------------------------------------------------------------------------------------------------------------------------
Hello, I also encountered this problem. I used import-data to create the initial data table. After the vulnerability data collection was completed, I checked the database. There was no record update record in the meta table. I think this should cause 【AttributeError:'NoneType' object has no attribute'value' 】error The reason, but I don’t know how to solve it, I hope to get your help. 

![image](https://user-images.githubusercontent.com/40291952/110453334-0728d900-8101-11eb-9425-eab245fec8ca.png)

**Comment by ncrocfer** [comment]
The `import-data` command uses a lot of RAM, and the meta table is populated in last.
Check the issue #5, I think it's a duplicate (you didn't have enought memory, so process was killed in middle of import).

**Comment by A1oha** [comment]
> 命令使用大量的RAM，元表最后填充。
> [检查问题#5，](https://github.com/opencve/opencve/issues/5)我认为这是一个重复（你没有足够的内存，所以过程在进口过程中被杀死）。`import-data`

----------------------------------------------------------------------------------------------------------------
Thank you very much. After adjusting the memory to 5.5GB, I solved the error

**Comment by gitworldhero** [comment]
thanks
