### ISSUE TITLE
opencve celery & webserver run error

### ISSUE THREAD

**Issue by topsekadmin** [opencve/opencve#73]
[root@cve opencve]# /usr/local/python3/bin/opencve celery worker -l INFO
Traceback (most recent call last):
  File "/usr/local/python3/bin/opencve", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/opencve/commands/__init__.py", line 39, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/opencve/commands/celery.py", line 21, in worker
    os.execvp(args[0], args)
  File "/usr/local/python3/lib/python3.7/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/usr/local/python3/lib/python3.7/os.py", line 616, in _execvpe
    raise last_exc
  File "/usr/local/python3/lib/python3.7/os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory

[root@cve opencve]# /usr/local/python3/bin/opencve webserver
Traceback (most recent call last):
  File "/usr/local/python3/bin/opencve", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/opencve/commands/__init__.py", line 39, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/opencve/commands/webserver.py", line 17, in webserver
    os.execvp(args[0], args)
  File "/usr/local/python3/lib/python3.7/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/usr/local/python3/lib/python3.7/os.py", line 616, in _execvpe
    raise last_exc
  File "/usr/local/python3/lib/python3.7/os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory

os version:CentOS Linux release 7.7.1908 (Core)
python version:Python 3.7.9

**Comment by ncrocfer** [comment]
How did you install OpenCVE ?

**Comment by topsekadmin** [comment]
> How did you install OpenCVE ?

i use pip install opencve,then install redis-cli 5.0.3 and postgresql13

**Comment by qlxmy** [comment]
i have the same problem

**Comment by Kogelvis** [comment]
I've ran into this as well today, but this was after installing opencve inside a virtualenv and trying to
run the opencve processes from systemd unit files. It took some effort and googling but I've managed to solve it.
In my case the virtualenv root directory is `/opt/opencve`

I've used the following unit-files to start the processes, maybe you can start the processes the same way from the command-line using each `ExecStart` command? (change paths to match your setup)

opencve-worker.service
```
[Unit]
Description=OpenCVE Celery Worker
After=network.target
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/opt/opencve/bin/celery worker -A opencve.app:cel -l INFO
WorkingDirectory=/opt/opencve
User=opencve
Group=opencve

[Install]
WantedBy=multi-user.target
```

opencve-beat.service
```
[Unit]
Description=OpenCVE Celery Beat
After=network.target
After=network-online.target
After=opencve-worker.target
Wants=network-online.target
Wants=opencve-worker.target

[Service]
ExecStart=/opt/opencve/bin/celery beat -A opencve.app:cel -l INFO
WorkingDirectory=/opt/opencve
User=opencve
Group=opencve

[Install]
WantedBy=multi-user.target
```

opencve-webserver.service
```
[Unit]
Description=OpenCVE WebServer
After=network.target
After=network-online.target
After=opencve-beat.target
Wants=network-online.target
Wants=opencve-beat.target

[Service]
ExecStart=/opt/opencve/bin/gunicorn -b 0.0.0.0:8000 opencve.app:app
WorkingDirectory=/opt/opencve
User=opencve
Group=opencve

[Install]
WantedBy=multi-user.target
```

**Comment by ncrocfer** [comment]
Thanks for your help @Kogelvis , I'm sure @topsekadmin  and @qlxmy appreciate it, even if they don't answer to you :)

I close this issue because it's not directly related to OpenCVE, but to users specific installation.
